(lang dune 3.21)

(generate_opam_files false)
(executables_implicit_empty_intf true)

(name ysun)
(version 2026.830.0)
(source (github stepbrobd/ysun))
(license GPL-3.0-or-later)
(authors "Yifei Sun <ysun@duck.com>")
(maintainers "Yifei Sun <ysun@duck.com>")

(package
  (name ysun)
  (depends
   cmdliner
   dune-build-info
   ocaml
   yocaml
   yocaml_eio
   yocaml_liquid
   yocaml_omd
   yocaml_syndication
   yocaml_yaml))
