# disabled: switched to cloudflare pages

name: "Fly"
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Fly:
    runs-on: "ubuntu-latest"

    permissions:
      id-token: "write"
      contents: "read"

    steps:
      - uses: "actions/checkout@v4"
        name: "Checkout"
        with:
          fetch-depth: 0

      - name: "Setup"
        uses: determinatesystems/nix-installer-action@main

      - name: "Check"
        uses: DeterminateSystems/flake-checker-action@main

      - name: "Deploy"
        run: nix run .#deploy --option sandbox false
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
