name: Release

permissions:
  contents: write
  id-token: write
  attestations: write

on:
  workflow_dispatch: null
  push:
    branches:
      - master

jobs:
  Workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Build
        run: |
          nix-store --dump $(nix build --option sandbox false --no-link --print-out-paths .#site) > site.nar
          nix-store --dump $(nix build --option sandbox false --no-link --print-out-paths .#exec) > exec.nar

      - name: Tag
        run: |
          echo "TAG=$(date +%Y.%m.%d.%H.%M.%S)" >> ${GITHUB_ENV}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: |
            site.nar
            exec.nar

      - name: Attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            site.nar
            exec.nar
