name: Release

permissions:
  contents: write
  id-token: write
  attestations: write

on:
  workflow_dispatch: null
  push:
    branches:
      - master

jobs:
  Workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Build
        run: |
          TAG=$(date +%Y.%m.%d.%H.%M.%S)
          echo "TAG=$TAG" >> ${GITHUB_ENV}

          nix-store --dump $(nix build --option sandbox false --no-link --print-out-paths .#site) > site.nar
          nix-store --dump $(nix build --option sandbox false --no-link --print-out-paths .#exec) > exec.nar

          SRI_SITE=$(nix hash file site.nar)
          SRI_EXEC=$(nix hash file exec.nar)

          cat << EOF >> ${GITHUB_ENV}
          BODY=\```\```\```nix
            packages.default =
              let
                importnar = name: url: hash: import <nix/fetchurl.nix> {
                  inherit name url hash;
                  unpack = true;
                };
                exec = importnar
                  "exec"
                  "https://github.com/stepbrobd/ysun/releases/download/${TAG}/exec.nar"
                  "${SRI_EXEC}";
                site = importnar
                  "site"
                  "https://github.com/stepbrobd/ysun/releases/download/${TAG}/site.nar"
                  "${SRI_SITE}";
              in
              pkgs.writeShellApplication {
                meta.platforms = [ "x86_64-linux" ];
                name = "ysun";
                runtimeInputs = [ exec site ];
                text = ''
                  exec \${exec}/bin/exec \${site} "\$@"
                '';
              };
          \```\```\```
          EOF

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ env.BODY }}
          tag_name: ${{ env.TAG }}
          files: |
            site.nar
            exec.nar

      - name: Attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            site.nar
            exec.nar
